"""Default-behaviour byte-identity guard for knob-consistent routing.

Knob-consistent routing (``modules/hooks-routing/.../knob_consistency.py``)
adds a level-3 "inherited caller intent" step to role resolution. Its whole
licence to exist is that it changes NOTHING for a matrix without a ``preset:``
block. Arguments do not establish that; a recording does.

``tests/fixtures/resolution_golden_pre_knob_consistency.json`` was generated by
running the resolver at commit ``99d9b08`` -- the tip of ``main`` immediately
BEFORE this feature -- over every shipped matrix and every role, against a
fixed fake provider roster. This test replays the identical harness against the
current tree and asserts the results are equal, entry for entry.

A matrix added AFTER that commit has no pre-feature answer, so it cannot be in
the recording. It is declared in ``NEW_SINCE_RECORDING`` and locked instead by
``NEW_MATRIX_EXPECTATIONS`` -- an explicit, hand-written role -> (provider,
model, effort) map checked by ``test_new_matrix_resolution_is_locked``. Both
declarations are required: a name in one without the other fails.

If this test fails, the default path moved. That is either a bug in the feature
or a deliberate routing change; either way it must be named in a PR body and
the fixture regenerated on purpose, never silently.

Regenerating (only when a routing change is intended and reviewed)::

    python3 tests/test_default_resolution_unchanged.py --regenerate
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, MagicMock

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
ROUTING_DIR = REPO_ROOT / "routing"
GOLDEN_PATH = (
    Path(__file__).parent / "fixtures" / "resolution_golden_pre_knob_consistency.json"
)

sys.path.insert(0, str(REPO_ROOT / "modules" / "hooks-routing"))

from amplifier_module_hooks_routing.resolver import (  # noqa: E402
    resolve_model_role,
)

# A fixed roster, so the recording is a function of the CODE and the MATRICES
# only -- never of what a live provider happened to list on the day.
FAKE_MODELS: dict[str, list[str]] = {
    "anthropic": [
        "claude-opus-5",
        "claude-opus-4-8",
        "claude-sonnet-5",
        "claude-haiku-4-5",
        "claude-fable-5-1",
    ],
    "openai": [
        "gpt-5.6-sol",
        "gpt-5.6-terra",
        "gpt-5.6-luna",
        "gpt-5.6-mini",
        "gpt-5.6-nano",
        "gpt-5.6",
        "gpt-5.5",
    ],
    "gemini": ["gemini-3-pro-preview", "gemini-3-flash-preview"],
    "github-copilot": ["claude-sonnet-4.6", "claude-opus-4.6", "gpt-5.5"],
    "ollama": ["qwen3.6-35b", "llama4-70b"],
}

# Matrices that ship a `preset:` block on purpose, and so are NOT part of the
# pre-feature recording. Adding a name here is a deliberate, reviewable act.
#
# `openai.yaml` gained a preset on 2026-09-02 (default ON -- a measured win
# on OpenAI roots, see README "Knob-consistent delegation"). It stays in the
# byte-identity check below regardless: `_snapshot()` never reads or passes
# `preset:`/`caller_context` to `resolve_model_role`, so a preset block is
# structurally inert for this cold-resolution recording -- see
# `test_preset_bearing_matrix_is_stock_without_a_caller` for the same
# invariant asserted directly. Listed here only so a future `--regenerate`
# does not need to re-derive that this file carries one on purpose.
PRESET_BEARING = {"openai-knob-consistent.yaml", "openai.yaml"}

# Matrices that did not EXIST when the pre-feature recording was taken, and so
# have no pre-feature answer to be identical to. They are not exempt from
# checking -- they are checked by `test_new_matrix_resolution_is_locked` below,
# against an explicit expectation written out in full here.
#
# This set exists so the two honest options for a NEW matrix are both visible:
# either it belongs in the recording (it does not -- the recording is a
# snapshot of commit 99d9b08, and appending to it would misstate the fixture's
# provenance), or it carries a `preset:` block (it does not -- see the file's
# own header for why that is deliberate). Silently adding it to either set
# would exempt it from every check in this module, which is the exact failure
# `test_golden_covers_every_pre_existing_matrix` was written to prevent.
#
# `openai-cheap-fast.yaml` added 2026-09-02 (lane ytg-presets-revision): a
# cheap-rung-everywhere OpenAI matrix. Gate evidence:
# docs/lanes/ytg-presets-revision/{PREREGISTRATION,FINDINGS}.md.
NEW_SINCE_RECORDING = {"openai-cheap-fast.yaml"}

# The lock for every name in NEW_SINCE_RECORDING: role -> (provider, model,
# reasoning_effort) under FAKE_MODELS. Written by hand from the matrix's stated
# contract, NOT generated from the file -- a generated expectation would agree
# with any future edit and check nothing.
NEW_MATRIX_EXPECTATIONS: dict[str, dict[str, tuple[str, str, str | None]]] = {
    # Contract: EVERY role on the cheap rung at medium, whatever the root.
    "openai-cheap-fast.yaml": {
        role: ("openai", "gpt-5.6-luna", "medium")
        for role in (
            "general",
            "fast",
            "coding",
            "ui-coding",
            "security-audit",
            "reasoning",
            "critique",
            "creative",
            "writing",
            "research",
            "vision",
            "image-gen",
            "critical-ops",
        )
    },
}


def _fake_providers() -> dict[str, Any]:
    providers: dict[str, Any] = {}
    for name, models in FAKE_MODELS.items():
        provider = MagicMock()
        provider.list_models = AsyncMock(return_value=list(models))
        providers[name] = provider
    return providers


async def _snapshot() -> dict[str, dict[str, Any]]:
    """Resolve every role of every shipped matrix, with NO caller context."""
    snapshot: dict[str, dict[str, Any]] = {}
    for path in sorted(ROUTING_DIR.glob("*.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        roles = (data or {}).get("roles") or {}
        per_matrix: dict[str, Any] = {}
        for role in roles:
            per_matrix[role] = await resolve_model_role(
                [role], roles, _fake_providers()
            )
        # The ordered-fallback contract, exercised explicitly: an unknown role
        # must fall through to the next one rather than resolve to nothing.
        per_matrix["__fallback__reasoning_then_general"] = await resolve_model_role(
            ["nonexistent-role", "reasoning", "general"], roles, _fake_providers()
        )
        snapshot[path.name] = per_matrix
    return snapshot


def _load_golden() -> dict[str, Any]:
    return json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))


def test_golden_fixture_exists() -> None:
    """Guards against a fixture deleted or moved out from under the test."""
    assert GOLDEN_PATH.exists(), f"missing golden fixture: {GOLDEN_PATH}"
    assert _load_golden(), "golden fixture is empty"


def test_golden_covers_every_pre_existing_matrix() -> None:
    """A new matrix must either be recorded or declared preset-bearing.

    Without this, dropping a matrix from the recording would silently exempt
    it from the identity check.
    """
    on_disk = {p.name for p in ROUTING_DIR.glob("*.yaml")}
    recorded = set(_load_golden())
    unaccounted = on_disk - recorded - PRESET_BEARING - NEW_SINCE_RECORDING
    assert not unaccounted, (
        "these matrices are neither in the pre-feature recording, nor declared "
        "preset-bearing, nor declared new-since-recording (with a lock in "
        f"NEW_MATRIX_EXPECTATIONS): {sorted(unaccounted)}"
    )
    stale = NEW_SINCE_RECORDING - on_disk
    assert not stale, f"declared new-since-recording but not on disk: {sorted(stale)}"
    vanished = recorded - on_disk
    assert not vanished, f"recorded matrices no longer on disk: {sorted(vanished)}"


@pytest.mark.parametrize(
    "matrix_name", sorted(_load_golden()), ids=lambda n: n.replace(".yaml", "")
)
def test_resolution_is_byte_identical_to_pre_feature(matrix_name: str) -> None:
    """Every role of every pre-existing matrix resolves exactly as it did."""
    golden = _load_golden()[matrix_name]
    current = asyncio.run(_snapshot())[matrix_name]
    assert current == golden, (
        f"{matrix_name}: default-path resolution CHANGED.\n"
        f"  expected (pre-feature): {json.dumps(golden, sort_keys=True)}\n"
        f"  actual   (this tree):   {json.dumps(current, sort_keys=True)}"
    )


def test_every_new_matrix_declares_a_lock() -> None:
    """No name may sit in NEW_SINCE_RECORDING without an explicit expectation.

    Without this, adding a name to that set would be a silent exemption from
    every check in this module -- exactly what the coverage test above exists
    to prevent.
    """
    missing = NEW_SINCE_RECORDING - set(NEW_MATRIX_EXPECTATIONS)
    assert not missing, (
        f"declared new-since-recording but unlocked: {sorted(missing)} -- add "
        "their full role->(provider, model, effort) expectation to "
        "NEW_MATRIX_EXPECTATIONS"
    )
    orphan = set(NEW_MATRIX_EXPECTATIONS) - NEW_SINCE_RECORDING
    assert not orphan, f"locked but not declared new-since-recording: {sorted(orphan)}"


@pytest.mark.parametrize(
    "matrix_name", sorted(NEW_SINCE_RECORDING), ids=lambda n: n.replace(".yaml", "")
)
def test_new_matrix_resolution_is_locked(matrix_name: str) -> None:
    """A matrix added after the recording resolves exactly as it declares.

    Same harness, same fake roster, same cold (no-caller) resolution as the
    identity check above -- only the reference differs: a hand-written
    expectation instead of a recording.
    """
    expected = NEW_MATRIX_EXPECTATIONS[matrix_name]
    current = asyncio.run(_snapshot())[matrix_name]
    actual = {
        role: (
            (
                str(res[0].get("provider")),
                str(res[0].get("model")),
                (res[0].get("config") or {}).get("reasoning_effort"),
            )
            if (res := current.get(role))
            else None
        )
        for role in expected
    }
    assert actual == expected, (
        f"{matrix_name}: resolution does not match its declared contract.\n"
        f"  expected: {json.dumps({k: list(v) for k, v in expected.items()}, sort_keys=True)}\n"
        f"  actual:   {json.dumps({k: list(v) if v else None for k, v in actual.items()}, sort_keys=True)}"
    )


def test_preset_bearing_matrix_is_stock_without_a_caller() -> None:
    """A preset changes nothing until a caller context exists.

    The `preset:` block is opt-in twice over: a matrix must carry one, AND the
    resolution must be handed a caller triple. Resolved cold -- the way every
    non-delegation consumer resolves -- the knob-consistent matrix returns the
    stock openai answers.
    """
    snapshot = asyncio.run(_snapshot())
    knob = snapshot.get("openai-knob-consistent.yaml")
    stock = snapshot.get("openai.yaml")
    assert knob is not None and stock is not None
    assert knob == stock


if __name__ == "__main__":  # pragma: no cover - maintenance entry point
    if "--regenerate" in sys.argv:
        snapshot = asyncio.run(_snapshot())
        skip = PRESET_BEARING | NEW_SINCE_RECORDING
        snapshot = {k: v for k, v in snapshot.items() if k not in skip}
        GOLDEN_PATH.write_text(
            json.dumps(snapshot, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        print(f"regenerated {GOLDEN_PATH} ({len(snapshot)} matrices)")
    else:
        print(__doc__)
